### ISSUE TITLE
Craft 4 Update?

### ISSUE THREAD

**Issue by gjhead** [croxton/imgixer#5]
Are there plans to update this plugin for Craft 4?

**Comment by croxton** [comment]
Yes, I'm working on it:
https://github.com/croxton/imgixer/tree/develop-v4

**Comment by gjhead** [comment]
Awesome. If you need any help testing, let me know. Happy to help!

**Comment by croxton** [comment]
@gjhead I tagged a Craft 4 beta release. Please try it out and let me know how you get on!

**Comment by terryupton** [comment]
@croxton when do you expect this to beta of beta and stable?

**Comment by croxton** [comment]
@terryupton the beta label still feels right because I've been tweaking the API slightly to accommodate multiple providers now that Imgix price plans have changed (Imgix, Imagekit and eventually Cloudinary and Cloudflare Images). The stable release will nonetheless be backward compatible for those upgrading from earlier versions. I'm fairly close to a stable version that supports Imgix and Imagekit; I would say most likely January.

**Comment by terryupton** [comment]
Perfect. Thanks @croxton. It's also great your looking to support other services as well. Because imgix outside the free plan is incredibly expensive now.
