### ISSUE TITLE
Subfolder setting

### ISSUE THREAD

**Issue by terryupton** [croxton/imgixer#7]
Hey @croxton

Hoping you can help me as I am struggling with one concept of this plugin. 

What is the best way to use the subfolder setting if a client creates new sub folders or chooses an image from a choice of different asset folders or sub folders? Or if I am setting the asset folder dynamically. For example, I have a projects section and each project creates a sub folder for the assets for that project (based on slug). 

The later we know, based on the project, so possibly could be coded in the template, the former, we don't as it is dependant upon the client and which folder they choose the image from. 

Whats the best way to tackle this? 
I am coming from ImagerX and they took care of this, in the config where you would do something like so:
```
 'addPath'                    => [
          'images'    => 'images',
          'projects'  => 'projects',
          'general'   => 'general',
          'bioImages' => 'bio-images',
        ],
```

**Comment by terryupton** [comment]
I should add that if I omit `subfolder` setting I get the following error:
`Getting unknown property: craft\fs\Local::subfolder`
<img width="1567" alt="Screenshot 2022-12-14 at 11 31 02" src="https://user-images.githubusercontent.com/5698596/207584241-be734a37-9a8f-43b6-82ee-fb462679e0c7.png">

**Comment by terryupton** [comment]
This is looks like a possible approach:
```twig
{% for image in bannerImages %}
  {% set source = image.volume.handle %}
  <figure>
    <img
      srcset="{{ image | imgix({source:source, from:600, to:2000 }) }}"
      src="{{ image | imgix({ source:source, w:800 }) }}"
      alt=""
    >
  </figure>
{% endfor %}
```
However, is there a cleaner solution so we don't have to set the ` image.volume.handle` each time and have to match this with a source, and have the plugin handle this at all?
Thanks.

**Comment by croxton** [comment]
The subfolder parameter was previously used to indicate the filesystem subfolder containing your images, rather than any child folders that are managed _within_ the Assets volume attached to the filesystem. But now that Imgixer works with the Asset object passed in Twig instead of raw image paths it can get that filesystem subfolder dynamically, so the parameter is no longer required _except_ when you have set up Imgix or Imagekit as a full proxy (which most people don't).

You should be able to omit the parameter from the Imgixer config, but unfortunately it looks like Imgixer is expecting you to have have created a Filesystem in Craft *with a subfolder* (e.g. 'images') if you haven't. It should work even if you don't specify a subfolder in the Craft filesystem, so that's a bug I'll need to fix. In the meantime it should work if you edit your Filesystem and add a subfolder to store your images in.

**Comment by croxton** [comment]
Just to add an example, here I'm using a Google Cloud Storage bucket connected to Imgix. I manually created the 4 folders you see here.

<img width="882" alt="Screenshot 2022-12-14 at 11 18 44" src="https://user-images.githubusercontent.com/279127/207593628-13352e4d-3211-4d6e-aa74-bc2b85ef3a3d.png">

I then created 4 filesystems using the same bucket with subfolders 'images', 'files', 'stock' and 'videos' respectively, with corresponding Asset volume for each filesystem:

<img width="1246" alt="Screenshot 2022-12-14 at 11 20 27" src="https://user-images.githubusercontent.com/279127/207594074-1efbe54d-0cb6-4e49-976b-addfed7a6698.png">

My config looks like this:

```php
'mysource' => array(
    'domain'   => 'mysource.imgix.net',
    'defaultParams' => array(
        'auto' => 'compress,format',
        'fit' => 'crop',
        'q' => '80'
    )
),
```

**Comment by croxton** [comment]
Ah ok, just checking you're using Craft 4? What type of storage are you using?

**Comment by terryupton** [comment]
> Ah ok, just checking you're using Craft 4? What type of storage are you using?
It is `Web Folder`.
<img width="476" alt="Screenshot 2022-12-14 at 12 42 19" src="https://user-images.githubusercontent.com/5698596/207598222-4e7000df-1712-4876-bc1f-f19f55b88b6c.png">

**Comment by croxton** [comment]
Hey Terry, I found and fixed the bug - local filesystem types don't have a 'subfolder' property. 

To try out the latest version of the plugin set your semver like this:

```json
"croxton/imgixer": "dev-feature/imagekit as 2.0.0-beta.1"
```

Then run
```
composer clear-cache && composer update
```

Docs for this branch of Imgixer are here:
https://github.com/croxton/imgixer/tree/feature/imagekit

Couple things to note:

First, this might be obvious to you, but to be clear if you are using a local filesystem that it isn't accessible to the web, Imgix (or imagekit) can't fetch images from it. Imgixer will still generate the correct URLs but you won't see any images when looking at your site in your local development environment (unless the images are in exactly the same place on your production environment that Imgix actually points to). It's usually best to use cloud storage if you can.

Second, when using a local filesystem with Imgix I'm going to assume that you have setup Imgix in 'webfolder' mode to point the _root_ folder that contains your volumes (images, projects, general and bioImages). E.g. if Imgix is pointing to `uploads` (`https://mywebsite.com/uploads/`), and you have this structure:

uploads
⌞ images
⌞ projects
⌞ general

In that case you would indeed need to use the `subfolder` parameter in your config for each of the volumes you want to use with Imgix, so that the URLs contain the correct path:

Example:

```php
'images' => array(
    'provider' => 'imgix',
    'subfolder' => 'images',
    'endpoint' => getenv('IMGIX_URL'),
    'privateKey' => getenv('IMGIX_KEY'),
    'signed' => true,
    'defaultParams' => array(
        'auto' => 'format',
        'q' => '80'
    )
),

'projects' => array(
    'provider' => 'imgix',
    'subfolder' => 'projects',
    'endpoint' => getenv('IMGIX_URL'),
    'privateKey' => getenv('IMGIX_KEY'),
    'signed' => true,
    'defaultParams' => array(
        'auto' => 'format',
        'q' => '80'
    )
),

```

Which you could use like this:

```twig
{{ image | imgix({source:image.volume.handle, from:600, to:2000 }) }}
```

If you want to avoid the two issues above then using Google Cloud Storage, S3 or one of the other cloud storage solutions would make things more straightforward.

**Comment by terryupton** [comment]
Hey Mark.
Thanks for the fixes on the branch. I am can confirm I am no longer seeing that issue/error.
Also, thanks for clarifying the subfolder part and that this IS required to match the source, and that we require a source to match each volume and to set this using `source:image.volume.handle`. 

The first part regarding local assets is fine and I was already aware of this. All images and imgix point to the staging server.

I guess to avoid duplication and set some general defaults for all sources, I can do something like this, rather than duplicate this code for each source.

```php
<?php

$default_params = [
  'auto' => 'compress,format,enhance',
  'fit'  => 'crop',
  'ar'   => '8:5',
  'step' => '100',
  'q'    => '80'
];

return [
  'sources' => array(

    // A unique handle that you can reference in your templates.
    'images' => array(
      'subfolder'     => 'images',
      'endpoint'      => getenv('IMGIX_URL'),
      'key'           => getenv('IMGIX_KEY'),
      'signed'        => true,
      'defaultParams' => $default_params
    ),

    'caseStudies' => array(
      'subfolder'     => 'case-studies',
      'endpoint'      => getenv('IMGIX_URL'),
      'key'           => getenv('IMGIX_KEY'),
      'signed'        => true,
      'defaultParams' => $default_params
    ),
  ),
```
<img width="628" alt="Screenshot 2022-12-14 at 15 42 40" src="https://user-images.githubusercontent.com/5698596/207641405-7fad0fcc-c937-4904-a239-5d5bd7db152c.png">

Thanks for your help so far. I might try and signup for ImageKit and give this a test as well, if I have some time available.

**Comment by croxton** [comment]
@terryupton yep that would work, or even just merge with a default:

```php

$defaults = array(
    'provider' => 'imgix',
    'endpoint' => getenv('IMGIX_URL'),
    'privateKey' => getenv('IMGIX_KEY'),
    'signed' => true,
    'defaultParams' => array(
        'auto' => 'format',
        'q' => '80'
    )
);

return [
    'sources' => array(
        'images' => array_merge($defaults, array(
            'subfolder' => 'images',
        )),
    ),
];
```
